In [1]:
##enumerate함수: 열거하다.
##많은 양의 데이터인 list를 다룰 때 편리하게 쓸 수 있는 기능을 제공
##for-each, for
#for x in list(포이치문): 리스트에 있는 것들을 하나씩 꺼내서 처리하기에 아주 간단
#                         index가 없어서 불편
#                         하나씩 꺼내서 출력, 연산하기는 용이
#                         리스트에 입력은 안된다.
# for i in range(n)(원래포문):리스트의 입력과 출력이 다 됨.
#                             인덱스로 리스트에 있는 값들을 접근해야하기 때문에 
#                             코드가 복잡하게 보인다.

In [2]:
# 주요 라이브러리 import
import warnings
warnings.filterwarnings(action='ignore')
import time
from IPython.display import Image
from sklearn.datasets import fetch_openml
import sklearn.datasets as data
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import LabelEncoder#라벨인코더 임포트
from sklearn.model_selection import KFold

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [3]:
num_list = [100,200,300]

In [4]:
for x in num_list:
    print(x+100)

200
300
400


In [5]:
for x in enumerate(num_list):#enumerate:튜플로 인덱스가 붙어서 나오게 해준다.
    print(x)

(0, 100)
(1, 200)
(2, 300)


In [6]:
for i,x in enumerate(num_list):#enumerate:튜플로 인덱스가 붙어서 나오게 해준다.
    print(i,':',x)#i에 인덱스 넣고 x에 값 넣어서 출력

0 : 100
1 : 200
2 : 300


In [7]:
for i,x in enumerate(num_list):#enumerate:튜플로 인덱스가 붙어서 나오게 해준다.
    num_list[i] = x+100

In [8]:
#포이치문은 인덱스가 없어서 리스트값을 바꾸는게 불가능했는데
#enumerate함수를 사용하면 가능해진다.
num_list

[200, 300, 400]

In [9]:
from sklearn.model_selection import KFold

In [10]:
kfold = KFold(n_splits=5)


In [11]:
titanic_df = pd.read_csv('./titanic_train.csv')
(titanic_df.head())

pclass  survived                               name     sex   age  sibsp  \
0       2         1  Mellinger, Miss. Madeleine Violet  female  13.0      0   
1       2         1                  Wells, Miss. Joan  female   4.0      1   
2       2         1     Duran y More, Miss. Florentina  female  30.0      1   
3       3         0                 Scanlan, Mr. James    male   NaN      0   
4       3         1       Bradley, Miss. Bridget Delia  female  22.0      0   

   parch         ticket     fare cabin embarked  body  \
0      1         250644  19.5000   NaN        S   NaN   
1      1          29103  23.0000   NaN        S   NaN   
2      0  SC/PARIS 2148  13.8583   NaN        C   NaN   
3      0          36209   7.7250   NaN        Q   NaN   
4      0         334914   7.7250   NaN        Q   NaN   

                                           home.dest  
0                           England / Bennington, VT  
1                               Cornwall / Akron, OH  
2                    Barcelona, Spain / Havana, Cuba  
3                                                NaN  
4  Kingwilliamstown, Co Cork, Ireland Glens Falls...

In [12]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     898 non-null    int64  
 1   survived   898 non-null    int64  
 2   name       898 non-null    object 
 3   sex        898 non-null    object 
 4   age        728 non-null    float64
 5   sibsp      898 non-null    int64  
 6   parch      898 non-null    int64  
 7   ticket     898 non-null    object 
 8   fare       898 non-null    float64
 9   cabin      211 non-null    object 
 10  embarked   896 non-null    object 
 11  body       84 non-null     float64
 12  home.dest  516 non-null    object 
dtypes: float64(3), int64(4), object(6)
memory usage: 91.3+ KB


In [13]:
##함수(drop)
##name,ticket,body,home.dest
def drop_features(df):#타이타닉 df를 넣고
    df.drop(columns=['name','ticket','body','home.dest'],inplace=True)
    return df#결과값을 리턴

In [14]:
titanic_df =  drop_features(titanic_df)
titanic_df.head()

pclass  survived     sex   age  sibsp  parch     fare cabin embarked
0       2         1  female  13.0      0      1  19.5000   NaN        S
1       2         1  female   4.0      1      1  23.0000   NaN        S
2       2         1  female  30.0      1      0  13.8583   NaN        C
3       3         0    male   NaN      0      0   7.7250   NaN        Q
4       3         1  female  22.0      0      0   7.7250   NaN        Q

In [15]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    898 non-null    int64  
 1   survived  898 non-null    int64  
 2   sex       898 non-null    object 
 3   age       728 non-null    float64
 4   sibsp     898 non-null    int64  
 5   parch     898 non-null    int64  
 6   fare      898 non-null    float64
 7   cabin     211 non-null    object 
 8   embarked  896 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 63.3+ KB


In [16]:
##na처리
##age는 평균으로 채워주세요
##cabin은 N으로 채워주세요
##embarked는 N으로 채워주세요(fillna())
##na개수가 몇개인지 전체 카운트

In [17]:
def fillna(df):
    df['age'].fillna(df['age'].mean(), inplace=True)
    df['cabin'].fillna('N',inplace=True)    
    df['embarked'].fillna('N',inplace=True)     
    return df

In [18]:
titanic_df = fillna(titanic_df)
titanic_df

pclass  survived     sex        age  sibsp  parch      fare        cabin  \
0         2         1  female  13.000000      0      1   19.5000            N   
1         2         1  female   4.000000      1      1   23.0000            N   
2         2         1  female  30.000000      1      0   13.8583            N   
3         3         0    male  30.196882      0      0    7.7250            N   
4         3         1  female  22.000000      0      0    7.7250            N   
..      ...       ...     ...        ...    ...    ...       ...          ...   
893       3         0    male  17.000000      2      0    8.0500            N   
894       3         0    male  30.196882      0      0    7.8792            N   
895       1         0    male  64.000000      1      4  263.0000  C23 C25 C27   
896       3         1    male  19.000000      0      0    8.0500            N   
897       1         1  female  26.000000      1      0  136.7792          C89   

    embarked  
0          S  
1          S  
2          C  
3          Q  
4          Q  
..       ...  
893        S  
894        S  
895        S  
896        S  
897        C  

[898 rows x 9 columns]

In [19]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    898 non-null    int64  
 1   survived  898 non-null    int64  
 2   sex       898 non-null    object 
 3   age       898 non-null    float64
 4   sibsp     898 non-null    int64  
 5   parch     898 non-null    int64  
 6   fare      898 non-null    float64
 7   cabin     898 non-null    object 
 8   embarked  898 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 63.3+ KB


In [20]:
#라벨인코딩:sex,cabin,embarked

In [21]:
titanic_df['cabin'].head(10)

0      N
1      N
2      N
3      N
4      N
5      N
6    E36
7      N
8    C68
9    E24
Name: cabin, dtype: object

In [22]:
#cabin컬럼의 첫글자만 넣는걸로 바꾸기, 라벨링 인코딩 하기 위해
# df['cabin'] = df['cabin'].str[:1]
# df['cabin'].head(10)

In [23]:
#라벨링 함수화
def label_encoding(df):
    df['cabin'] = df['cabin'].str[:1]
    print(list(titanic_df['cabin'])[:10])    
    le = LabelEncoder()#라벨인코딩하는 객체 생성
    features = ['sex','cabin','embarked']
    for f in features:
        le.fit(df[f])#라벨인코딩 객체에 sex, cabin, embarked를 하나씩 fit시킴. fit 메서드를 통해서 해당 데이터 학습
        print('라벨링할 목록=>', le.classes_)
        df[f] =le.transform(df[f])
    return df

In [24]:
titanic_df = label_encoding(titanic_df)
titanic_df

['N', 'N', 'N', 'N', 'N', 'N', 'E', 'N', 'C', 'E']
라벨링할 목록=> ['female' 'male']
라벨링할 목록=> ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'N' 'T']
라벨링할 목록=> ['C' 'N' 'Q' 'S']


pclass  survived  sex        age  sibsp  parch      fare  cabin  embarked
0         2         1    0  13.000000      0      1   19.5000      7         3
1         2         1    0   4.000000      1      1   23.0000      7         3
2         2         1    0  30.000000      1      0   13.8583      7         0
3         3         0    1  30.196882      0      0    7.7250      7         2
4         3         1    0  22.000000      0      0    7.7250      7         2
..      ...       ...  ...        ...    ...    ...       ...    ...       ...
893       3         0    1  17.000000      2      0    8.0500      7         3
894       3         0    1  30.196882      0      0    7.8792      7         3
895       1         0    1  64.000000      1      4  263.0000      2         3
896       3         1    1  19.000000      0      0    8.0500      7         3
897       1         1    0  26.000000      1      0  136.7792      2         0

[898 rows x 9 columns]

In [25]:
titanic_df.head()

pclass  survived  sex        age  sibsp  parch     fare  cabin  embarked
0       2         1    0  13.000000      0      1  19.5000      7         3
1       2         1    0   4.000000      1      1  23.0000      7         3
2       2         1    0  30.000000      1      0  13.8583      7         0
3       3         0    1  30.196882      0      0   7.7250      7         2
4       3         1    0  22.000000      0      0   7.7250      7         2

In [26]:
#지금까지 만든함수 한번에 묶어서 불러주기.
def preprocessing(df):
    df2 = fillna(df)
    df3 = drop_features(df2)
    df4 = label_encoding(df3)
    return df4

In [27]:
titanic_df2 = pd.read_csv('./titanic_train.csv')
(titanic_df2.head())

pclass  survived                               name     sex   age  sibsp  \
0       2         1  Mellinger, Miss. Madeleine Violet  female  13.0      0   
1       2         1                  Wells, Miss. Joan  female   4.0      1   
2       2         1     Duran y More, Miss. Florentina  female  30.0      1   
3       3         0                 Scanlan, Mr. James    male   NaN      0   
4       3         1       Bradley, Miss. Bridget Delia  female  22.0      0   

   parch         ticket     fare cabin embarked  body  \
0      1         250644  19.5000   NaN        S   NaN   
1      1          29103  23.0000   NaN        S   NaN   
2      0  SC/PARIS 2148  13.8583   NaN        C   NaN   
3      0          36209   7.7250   NaN        Q   NaN   
4      0         334914   7.7250   NaN        Q   NaN   

                                           home.dest  
0                           England / Bennington, VT  
1                               Cornwall / Akron, OH  
2                    Barcelona, Spain / Havana, Cuba  
3                                                NaN  
4  Kingwilliamstown, Co Cork, Ireland Glens Falls...

In [28]:
#데이터 전처리 호출
titanic_df3 = preprocessing(titanic_df2)
titanic_df3

[7, 7, 7, 7, 7, 7, 4, 7, 2, 4]
라벨링할 목록=> ['female' 'male']
라벨링할 목록=> ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'N' 'T']
라벨링할 목록=> ['C' 'N' 'Q' 'S']


pclass  survived  sex        age  sibsp  parch      fare  cabin  embarked
0         2         1    0  13.000000      0      1   19.5000      7         3
1         2         1    0   4.000000      1      1   23.0000      7         3
2         2         1    0  30.000000      1      0   13.8583      7         0
3         3         0    1  30.196882      0      0    7.7250      7         2
4         3         1    0  22.000000      0      0    7.7250      7         2
..      ...       ...  ...        ...    ...    ...       ...    ...       ...
893       3         0    1  17.000000      2      0    8.0500      7         3
894       3         0    1  30.196882      0      0    7.8792      7         3
895       1         0    1  64.000000      1      4  263.0000      2         3
896       3         1    1  19.000000      0      0    8.0500      7         3
897       1         1    0  26.000000      1      0  136.7792      2         0

[898 rows x 9 columns]

In [29]:
titanic_df3.columns

Index(['pclass', 'survived', 'sex', 'age', 'sibsp', 'parch', 'fare', 'cabin',
       'embarked'],
      dtype='object')

In [81]:
data = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'cabin','embarked']
#train_test data split
X_train, X_test, y_train, y_test = train_test_split(
    #문제
    titanic_df3[data],
    #정답
    titanic_df3['survived'],
    #test-size비율
    test_size= 0.2,
    #시드값설정
    random_state=10
)

In [82]:
X_train.shape

(718, 8)

In [83]:
X_test.shape

(180, 8)

In [84]:
y_test.shape

(180,)

In [85]:
y_train.shape

(718,)

In [86]:
##8개의 변수로 1개의 target을 분류하는 문제!
##y = ax1 + bx2 +cx3 +dx4 +ex5 +fx6 + gx7+ hx8
##['pclass', 'survived', 'sex', 'age', 'sibsp', 'parch', 'fare', 'cabin',
       #'embarked']
## survived = a*pclass + b*sex+ age*c+ 
# +parch*e +fare*f +cabin*g +embarked*h +y절편
#이 되고 가장 합리적인 선을 찾는다.

In [87]:
df_clf = DecisionTreeClassifier(random_state=11)
rf_clf = RandomForestClassifier(random_state=11)
svc_clf = SVC()
clf_list = [df_clf, rf_clf, svc_clf]

In [88]:
#train 데이터 3가지 방법으로 훈련데이터 훈련시켜서
#정확도 비교
for clf in clf_list:
    clf.fit(X_train, y_train)
    pred = clf.predict(X_test)
    print('정확도>> {0:.4f}'.format(accuracy_score(y_test,pred)))

정확도>> 0.7833
정확도>> 0.8167
정확도>> 0.7111


In [89]:
kfold = KFold(n_splits=5)

In [90]:
#샘플데이터를 i번 바꿔서 다양하게 변화시키는것:k-fold
#인덱스(i)를 찍어보자
for i, (train_index, test_index) in enumerate(kfold.split(titanic_df3[data])):
    print(i,'-------------')
    print('test_index>> ',test_index)
    print('train_index>> ',train_index)    

0 -------------
test_index>>  [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179]
train_index>>  [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 

In [91]:
titanic_df3[data].head()

pclass  sex        age  sibsp  parch     fare  cabin  embarked
0       2    0  13.000000      0      1  19.5000      7         3
1       2    0   4.000000      1      1  23.0000      7         3
2       2    0  30.000000      1      0  13.8583      7         0
3       3    1  30.196882      0      0   7.7250      7         2
4       3    0  22.000000      0      0   7.7250      7         2

In [92]:
titanic_df3[data].values

array([[  2.    ,   0.    ,  13.    , ...,  19.5   ,   7.    ,   3.    ],
       [  2.    ,   0.    ,   4.    , ...,  23.    ,   7.    ,   3.    ],
       [  2.    ,   0.    ,  30.    , ...,  13.8583,   7.    ,   0.    ],
       ...,
       [  1.    ,   1.    ,  64.    , ..., 263.    ,   2.    ,   3.    ],
       [  3.    ,   1.    ,  19.    , ...,   8.05  ,   7.    ,   3.    ],
       [  1.    ,   0.    ,  26.    , ..., 136.7792,   2.    ,   0.    ]])

In [93]:
titanic_df3[data].values[[0,3]]#0,3번 인덱스 값만 가져옴.

array([[ 2.        ,  0.        , 13.        ,  0.        ,  1.        ,
        19.5       ,  7.        ,  3.        ],
       [ 3.        ,  1.        , 30.19688187,  0.        ,  0.        ,
         7.725     ,  7.        ,  2.        ]])

In [94]:
titanic_df3[data].values[test_index]

array([[  3.        ,   1.        ,  27.        , ...,   7.8958    ,
          7.        ,   3.        ],
       [  3.        ,   1.        ,  18.5       , ...,   7.2292    ,
          7.        ,   0.        ],
       [  1.        ,   0.        ,  30.19688187, ...,  79.2       ,
          7.        ,   0.        ],
       ...,
       [  1.        ,   1.        ,  64.        , ..., 263.        ,
          2.        ,   3.        ],
       [  3.        ,   1.        ,  19.        , ...,   8.05      ,
          7.        ,   3.        ],
       [  1.        ,   0.        ,  26.        , ..., 136.7792    ,
          2.        ,   0.        ]])

In [95]:
#이 값으로 검증을 하면 된다.
titanic_df3[data].values[train_index]

array([[ 2.        ,  0.        , 13.        , ..., 19.5       ,
         7.        ,  3.        ],
       [ 2.        ,  0.        ,  4.        , ..., 23.        ,
         7.        ,  3.        ],
       [ 2.        ,  0.        , 30.        , ..., 13.8583    ,
         7.        ,  0.        ],
       ...,
       [ 2.        ,  1.        , 44.        , ..., 13.        ,
         7.        ,  3.        ],
       [ 3.        ,  1.        , 21.        , ...,  6.4958    ,
         7.        ,  3.        ],
       [ 3.        ,  1.        , 30.19688187, ...,  7.8958    ,
         7.        ,  3.        ]])

In [96]:
titanic_df3['survived'].values[0:5]#리스트 중 인덱스 0~4개 추출

array([1, 1, 1, 0, 1], dtype=int64)

In [97]:
titanic_df3['survived'].values[[0,2,5]]#리스트 중 특정 인덱스 0,2,5만 추출

array([1, 1, 0], dtype=int64)

In [98]:
#샘플데이터를 i번 바꿔서 다양하게 변화시키는것:k-fold
#enumerate 쓰면 index가 같이 나오므로 i를 써줘야한다.
#(train_index, test_index)가 2개의 이차배열인 (kfold.split(titanic_df3[data]))의 0번째 1번째 값들이 된다.
# def exec_kfold(clf):
#     acc_list = []
#     kfold = KFold(n_splits=k)
#     for i, (train_index, test_index) in enumerate(kfold.split(titanic_df3[data])):
#         X_train2, X_test2=titanic_df3[data].values[train_index],titanic_df3[data].values[test_index]

#         y_train2, y_test2=titanic_df3['survived'].values[train_index],titanic_df3['survived'].values[test_index]
        
#         clf.fit(X_train2,y_train2)
#         pred2 = clf.predit(X_test2)
#         acc = accuracy_score(y_test2,pred2)
#         acc_list.append(acc)
#         print('정확도>>{0:4f}'.format(acc))
#     print('평균정확도>> ', np.mean(acc_list))

def exec_kfold(clf, k):
    acc_list = []
    kfold = KFold(n_splits=k)
    for i, (train_index, test_index) in enumerate(kfold.split(titanic_df3[data])):
        X_train2,X_test2 = titanic_df3[data].values[train_index], titanic_df3[data].values[test_index]
        y_train2,y_test2 = titanic_df3['survived'].values[train_index], titanic_df3['survived'].values[test_index]
        
        clf.fit(X_train2, y_train2)
        pred2 = clf.predict(X_test2)
        acc = accuracy_score(y_test2, pred2)
        acc_list.append(acc)
        print(i , ': 정확도>> {0:.2f}'.format(acc))
    print('평균 정확도>> {0:.2f}'.format(np.mean(acc_list)))

In [100]:
exec_kfold(df_clf, 5) 
#decision tree model을 가지고 cross-validation()

0 : 정확도>> 0.81
1 : 정확도>> 0.72
2 : 정확도>> 0.74
3 : 정확도>> 0.78
4 : 정확도>> 0.80
평균 정확도>> 0.77


In [101]:
exec_kfold(df_clf,10)

0 : 정확도>> 0.82
1 : 정확도>> 0.73
2 : 정확도>> 0.70
3 : 정확도>> 0.78
4 : 정확도>> 0.81
5 : 정확도>> 0.74
6 : 정확도>> 0.74
7 : 정확도>> 0.82
8 : 정확도>> 0.82
9 : 정확도>> 0.76
평균 정확도>> 0.77


In [105]:
exec_kfold(rf_clf,10)#렌덤포레스트

0 : 정확도>> 0.81
1 : 정확도>> 0.81
2 : 정확도>> 0.80
3 : 정확도>> 0.74
4 : 정확도>> 0.82
5 : 정확도>> 0.74
6 : 정확도>> 0.77
7 : 정확도>> 0.81
8 : 정확도>> 0.83
9 : 정확도>> 0.79
평균 정확도>> 0.79


In [102]:
##svm, rf 비교(5,10)=>평균!

In [103]:
##model list로 교차검증이 한꺼번에 되게 코드를 변경해보고,
##model list중 평균값의 교차검증 결과 중 최대인 모델의 평균값은>
##평균값이 제일 높은 모델을 선정해보세요!
## 제일 정확도가 높은 모델은 랜덤포레스트이고, 정확도는 88입니다.

In [104]:
# df_clf = DecisionTreeClassifier(random_state=11)
# rf_clf = RandomForestClassifier(random_state=11)
# svc_clf = SVC()
# clf_list = [df_clf, rf_clf, svc_clf]

In [106]:
titanic_df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    898 non-null    int64  
 1   survived  898 non-null    int64  
 2   sex       898 non-null    int32  
 3   age       898 non-null    float64
 4   sibsp     898 non-null    int64  
 5   parch     898 non-null    int64  
 6   fare      898 non-null    float64
 7   cabin     898 non-null    int32  
 8   embarked  898 non-null    int32  
dtypes: float64(2), int32(3), int64(4)
memory usage: 52.7 KB


In [107]:
#int형이라 안될 때!
pd.get_dummies(titanic_df3.loc[:, ['sex', 'cabin', 'embarked']])

sex  cabin  embarked
0      0      7         3
1      0      7         3
2      0      7         0
3      1      7         2
4      0      7         2
..   ...    ...       ...
893    1      7         3
894    1      7         3
895    1      2         3
896    1      7         3
897    0      2         0

[898 rows x 3 columns]

In [108]:
#category로 바꾸는 이유는 int값이면 숫자니까 원핫인코딩 안할수 있어서
#int값이긴 하지만 category라는 것을 알려주기 위함.
#카테고리형: (0~8)=>one-hot encoding의 대상이 된다.
             # 카테고리에 포함된 수치만 와야함
#age:연속형, 다른 수치가 와도 된다.
as_cate = titanic_df3[['sex', 'cabin', 'embarked']].astype('category')
as_cate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   sex       898 non-null    category
 1   cabin     898 non-null    category
 2   embarked  898 non-null    category
dtypes: category(3)
memory usage: 3.4 KB


In [109]:
titanic_df3.drop(columns=['sex', 'cabin', 'embarked'], inplace=True)

In [110]:
titanic_df4 = pd.concat([titanic_df3, as_cate], axis=1)
titanic_df4.columns

Index(['pclass', 'survived', 'age', 'sibsp', 'parch', 'fare', 'sex', 'cabin',
       'embarked'],
      dtype='object')

In [111]:
titanic_df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   pclass    898 non-null    int64   
 1   survived  898 non-null    int64   
 2   age       898 non-null    float64 
 3   sibsp     898 non-null    int64   
 4   parch     898 non-null    int64   
 5   fare      898 non-null    float64 
 6   sex       898 non-null    category
 7   cabin     898 non-null    category
 8   embarked  898 non-null    category
dtypes: category(3), float64(2), int64(4)
memory usage: 45.5 KB


In [112]:
# category로 변경 후 다시!
pd.get_dummies(titanic_df4)

pclass  survived        age  sibsp  parch      fare  sex_0  sex_1  \
0         2         1  13.000000      0      1   19.5000      1      0   
1         2         1   4.000000      1      1   23.0000      1      0   
2         2         1  30.000000      1      0   13.8583      1      0   
3         3         0  30.196882      0      0    7.7250      0      1   
4         3         1  22.000000      0      0    7.7250      1      0   
..      ...       ...        ...    ...    ...       ...    ...    ...   
893       3         0  17.000000      2      0    8.0500      0      1   
894       3         0  30.196882      0      0    7.8792      0      1   
895       1         0  64.000000      1      4  263.0000      0      1   
896       3         1  19.000000      0      0    8.0500      0      1   
897       1         1  26.000000      1      0  136.7792      1      0   

     cabin_0  cabin_1  ...  cabin_3  cabin_4  cabin_5  cabin_6  cabin_7  \
0          0        0  ...        0        0        0        0        1   
1          0        0  ...        0        0        0        0        1   
2          0        0  ...        0        0        0        0        1   
3          0        0  ...        0        0        0        0        1   
4          0        0  ...        0        0        0        0        1   
..       ...      ...  ...      ...      ...      ...      ...      ...   
893        0        0  ...        0        0        0        0        1   
894        0        0  ...        0        0        0        0        1   
895        0        0  ...        0        0        0        0        0   
896        0        0  ...        0        0        0        0        1   
897        0        0  ...        0        0        0        0        0   

     cabin_8  embarked_0  embarked_1  embarked_2  embarked_3  
0          0           0           0           0           1  
1          0           0           0           0           1  
2          0           1           0           0           0  
3          0           0           0           1           0  
4          0           0           0           1           0  
..       ...         ...         ...         ...         ...  
893        0           0           0           0           1  
894        0           0           0           0           1  
895        0           0           0           0           1  
896        0           0           0           0           1  
897        0           1           0           0           0  

[898 rows x 21 columns]

In [113]:
def exec_kfold2(df, clf, k):
    acc_list = []
    kfold = KFold(n_splits=k)
    for i, (train_index, test_index) in enumerate(kfold.split(df[data])):
        X_train2,X_test2 = df[data].values[train_index], df[data].values[test_index]
        y_train2,y_test2 = df['survived'].values[train_index],df['survived'].values[test_index]
        
        clf.fit(X_train2, y_train2)
        pred2 = clf.predict(X_test2)
        acc = accuracy_score(y_test2, pred2)
        acc_list.append(acc)
        print(i , ': 교차검증 정확도>> {0:.2f}'.format(acc))
    print('평균 정확도>> {0:.2f}'.format(np.mean(acc_list)))
    return np.mean(acc_list)

In [114]:
#decision tree와 randomforest와 svm를 시각화 하여 어떤 것을 사용하는게 합리적인지 보여줄 수 있다.
acc_total = []
model_list = ['decision tree', 'random forest', 'svm']
for i, clf in enumerate(clf_list):
    print(model_list[i], '----검증시작----')
    acc_result = exec_kfold2(titanic_df4, clf, 10)
    acc_total.append(acc_result)

decision tree ----검증시작----
0 : 교차검증 정확도>> 0.82
1 : 교차검증 정확도>> 0.73
2 : 교차검증 정확도>> 0.70
3 : 교차검증 정확도>> 0.78
4 : 교차검증 정확도>> 0.81
5 : 교차검증 정확도>> 0.74
6 : 교차검증 정확도>> 0.74
7 : 교차검증 정확도>> 0.82
8 : 교차검증 정확도>> 0.82
9 : 교차검증 정확도>> 0.76
평균 정확도>> 0.77
random forest ----검증시작----
0 : 교차검증 정확도>> 0.81
1 : 교차검증 정확도>> 0.81
2 : 교차검증 정확도>> 0.80
3 : 교차검증 정확도>> 0.74
4 : 교차검증 정확도>> 0.82
5 : 교차검증 정확도>> 0.74
6 : 교차검증 정확도>> 0.77
7 : 교차검증 정확도>> 0.81
8 : 교차검증 정확도>> 0.83
9 : 교차검증 정확도>> 0.79
평균 정확도>> 0.79
svm ----검증시작----
0 : 교차검증 정확도>> 0.62
1 : 교차검증 정확도>> 0.67
2 : 교차검증 정확도>> 0.64
3 : 교차검증 정확도>> 0.69
4 : 교차검증 정확도>> 0.73
5 : 교차검증 정확도>> 0.62
6 : 교차검증 정확도>> 0.63
7 : 교차검증 정확도>> 0.67
8 : 교차검증 정확도>> 0.70
9 : 교차검증 정확도>> 0.70
평균 정확도>> 0.67


In [115]:
for i in range(3):
    print(model_list[i], " 교차검증 평균: ", acc_total[i])

decision tree  교차검증 평균:  0.7739825218476903
random forest  교차검증 평균:  0.7929088639200998
svm  교차검증 평균:  0.6671036204744071


In [116]:
# 최대 평균값 ==
max_value = np.max(acc_total)
# 최대 평균값 인덱스 ==
max_index = np.argmax(acc_total)
# 최대 평균값 모델명 ==
max_model = model_list[max_index]

print('최고 교차 검증 평균>> ', max_value)
print('최고 교차 검증 인덱스>> ', max_index)
print('최고 교차 검증 모델링>> ', max_model)

최고 교차 검증 평균>>  0.7929088639200998
최고 교차 검증 인덱스>>  1
최고 교차 검증 모델링>>  random forest
